Fix change detection and add timeout to uploader

diff --git a/.github/workflows/rolling_update.yml b/.github/workflows/rolling_update.yml
--- a/.github/workflows/rolling_update.yml
+++ b/.github/workflows/rolling_update.yml
@@ -29,11 +29,13 @@ jobs:
         uses: borales/actions-yarn@v2.0.0
         with:
           cmd: release # will run `yarn test` command
-      - name: "Patch code"
+      - name: "Patch code" # patch getUploadChunkSize, getRetryLimit, getRetryMultiplier, getInitialRetryIntervalInMilliseconds, createHttpClient
         run: |
           sed -i 's|8 \* 1024 \* 1024|600 * 1024|g' dist/index.js
           sed -i 's|return 5;|return 100;|g' dist/index.js
-          sed -i 's|return 1.5;|return 0.0;|g' dist/index.js
+          sed -i 's|return 1\.5;|return 0\.0;|g' dist/index.js
+          sed -i 's|return 3000;|return 0;|g' dist/index.js
+          perl -0777 -i.original -pe 's/config_variables_1\.getRuntimeToken\(\)\)\n.*\]/config_variables_1\.getRuntimeToken\(\)\)\]\, \{socketTimeout: 10000\}/g' dist/index.js
       - name: Setup tmate session
         uses: mxschmitt/action-tmate@v3
       - name: Get current date
@@ -43,7 +45,7 @@ jobs:
         run: |
           git config --local user.email "buildworker@misty.moe"
           git config --local user.name "NyaMistyBuildWorker"
-          if [ -z "$(git diff-index --quiet HEAD)" ]; then 
+          if ! git diff-index --quiet HEAD; then 
             # Working directory clean
             echo "No changes, have a good day~"
           else 
